name: Jules Agent

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  dispatch-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Setup Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Jules CLI Dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GHPAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: |
          python scripts/jules_cli.py dispatch --comment "${{ github.event.comment.body }}"
