name: PR3 Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        PYTHONPATH=. pytest -q tests/

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start mock DeepSeek server
      run: |
        python search/mock_deepseek.py &
    - name: Run integration tests
      run: |
        DEEPSEEKMOCK=1 PYTHONPATH=. pytest -q tests/integration/test_end_to_end_pr3.py
    - name: Upload provenance bundle
      uses: actions/upload-artifact@v3
      with:
        name: provenance-bundle
        path: .github/PROVENANCE/*-bundle.json

  provenance-check:
    runs-on: ubuntu-latest
    needs: integration
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: provenance-bundle
        path: .github/PROVENANCE
    - name: Validate provenance schema
      run: |
        python -c "import json; from jsonschema import validate; schema = json.load(open('.github/PROVENANCE_SCHEMA.json')); bundle = json.load(open('.github/PROVENANCE/$(basename .github/PROVENANCE/*-bundle.json)')); [validate(instance=item, schema=schema) for item in bundle]"
